### ISSUE TITLE
TypeError: __new__() takes from 2 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by jesuscoppelia** [Nepherhotep/unwrap_labels#2]
Hello, i get this error in the first line:
TypeError: __new__() takes from 2 to 3 positional arguments but 4 were given

I have copy all your code, as you can see:

BLACK_COLOR = (0, 0, 0)
WHITE_COLOR = (255, 255, 255)
YELLOW_COLOR = (0, 255, 255)

vino = imageio.imread('vino1.png')

class Line(vino):
    def __init__(self, point1, point2):
       
        #For line formula y(x) = k * x + b, calc k and b params
        #If the line is vertical, set "vertical" attr to True and save "x" position of the line
        
        self.point1 = point1
        self.point2 = point2
        self.vertical = True
        self.fixed_x = None
        self.k = None
        self.b = None
        # cached angle props
        self.angle = None
        self.angle_cos = None
        self.angle_sin = None

        self.set_line_props(point1, point2)

Please, how can i solve this?

Thanks

**Comment by Nepherhotep** [comment]
Hey @jesuscoppelia 
Why do you nest from "vino" object, as it's just array? Can you instead create a branch with your script and image to let me run it in my sandbox?
